### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by prashantbohra01** [StagOS/android_packages_apps_Settings#4]
getting bluetooth error - bluetooth turning on and off automatically in realme x3 unofficial build 
help!
here are the logs :-- 

msg: java.lang.ArithmeticException: divide by zero
stacktrace: java.lang.RuntimeException: Unable to start service com.android.bluetooth.a2dp.A2dpService@48eaa6a with Intent { flg=0x10000000 cmp=com.android.bluetooth/.a2dp.A2dpService (has extras) }: java.lang.ArithmeticException: divide by zero
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4339)
	at android.app.ActivityThread.access$1800(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ArithmeticException: divide by zero
	at com.android.bluetooth.avrcp.Avrcp_ext.<init>(Avrcp_ext.java:477)
	at com.android.bluetooth.avrcp.Avrcp_ext.make(Avrcp_ext.java:608)
	at com.android.bluetooth.a2dp.A2dpService.start(A2dpService.java:238)
	at com.android.bluetooth.btservice.ProfileService.doStart(ProfileService.java:284)
	at com.android.bluetooth.btservice.ProfileService.onStartCommand(ProfileService.java:166)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4321)
	... 8 more

**Comment by kardebayan** [comment]
@4gravesgaming Painful life
